### ISSUE TITLE
Use function deprecated in Pillow 10.x

### ISSUE THREAD

**Issue by UNIkeEN** [UNIkeEN/Little-UNIkeEN-Bot#2]
These function deprecated in Pillow 10.x are used in this project:

`PIL.ImageFont.FreeTypeFont.getsize()`
`PIL.ImageDraw.textsize()`

And the `requirements.txt` does not specify the version of the `Pillow` library. If you meet problems like
```
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```
Please try to downgrade `Pillow` to 9.x or earlier, and we will fix this problem by using new alter functions (such as `PIL.ImageFont.FreeTypeFont.getbbox()`) in the future.

---

本项目使用了 Pillow 10.x 中已弃用的这些函数：

`PIL.ImageFont.FreeTypeFont.getsize()`
`PIL.ImageDraw.textsize()`

并且“requirements.txt”没有指定“Pillow”库的版本。 如果您遇到类似问题：
````
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
````
请尝试将`Pillow`降级到9.x或更早版本，之后我们将通过使用其他函数（如`PIL.ImageFont.FreeTypeFont.getbbox()`）来解决这个问题。

**Comment by UNIkeEN** [comment]
We have completed fixes to the `responseImage.py`, which is currently located in the `image_beta` branch and tested on `Pillow 10.1.0` and `Pillow 9.3.0`.

我们已经对 `responseImage` 库进行了修复（ `utils/responseImage.py`），目前存放于 `image_beta` 分支的版本在 `Pillow 10.1.0` 和`Pillow 9.3.0` 版本经过测试。

**Comment by fangtiancheng** [comment]
`image_beta` 分支已合入 `main` 分支，注意编写函数签名
![image](https://github.com/UNIkeEN/Little-UNIkeEN-Bot/assets/67567242/cc4172e7-5f24-4909-b671-903c433ec80f)
